#!/usr/bin/env bash

PATH="./node_modules/.bin:./../../../node_modules/.bin:$PATH"

[[ -f "./.env" ]] && source ./.env

function format {
  prettier --write "src/**/*.{js,jsx,ts,tsx,astro,json,css,md}"
}

function build {
  rm -rf ./dist
  tsc --project ./tsconfig.json
}

# TODO: create the test command using @openwc testing library
function test {
  echo "TODO!"
  exit 1
}

function help {
  echo "$0 <task> <args>"
  echo "Tasks:"
  compgen -A function | cat -n
}

TIMEFORMAT="Task completed in %3lR"
time "${@:-help}"
